"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Tab = "home" | "members" | "checkin" | "pt" | "reports" | "database";
type Member = { id:number; memberCode:string; fullName:string; phone:string; lineId:string|null; startsAt:string|null; expiresAt:string|null };
type Ops = { packages:any[]; sessions:any[]; assessments:any[]; visits:any[]; followups:any[]; payments:any[]; memberships:any[]; renewals:any[] };

function statusOf(expiresAt: string | null) {
  if (!expiresAt) return { label:"ยังไม่มีแพ็กเกจ", key:"expired", days:-1 };
  const today = new Date(); today.setHours(0,0,0,0);
  const end = new Date(`${expiresAt}T00:00:00`);
  const days = Math.ceil((end.getTime()-today.getTime())/86400000);
  if (days < 0) return { label:"หมดอายุ", key:"expired", days };
  if (days <= 7) return { label:"ใกล้หมดอายุ", key:"expiring", days };
  return { label:"Active", key:"active", days };
}

function thaiDate(value:string|null) {
  if (!value) return "—";
  return new Intl.DateTimeFormat("th-TH",{day:"numeric",month:"short",year:"numeric"}).format(new Date(`${value}T00:00:00`));
}

export default function Home() {
  const [tab,setTab]=useState<Tab>("home");
  const [members,setMembers]=useState<Member[]>([]);
  const [manager,setManager]=useState("Manager");
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState("");
  const [search,setSearch]=useState("");
  const [showAdd,setShowAdd]=useState(false);
  const [renew,setRenew]=useState<Member|null>(null);
  const [toast,setToast]=useState("");
  const [ops,setOps]=useState<Ops>({packages:[],sessions:[],assessments:[],visits:[],followups:[],payments:[],memberships:[],renewals:[]});
  const [action,setAction]=useState<{kind:string;member?:Member}|null>(null);

  async function load(){
    setLoading(true); setError("");
    try {
      const r=await fetch("/api/members",{cache:"no-store"});
      const d=await r.json();
      if(r.status===401){window.location.assign("/login");return}
      if(!r.ok)setError(d.error||"โหลดข้อมูลไม่สำเร็จ");
      else {setMembers(d.members);setManager(d.manager||"Manager");}
    } catch (loadError) {
      setError(loadError instanceof Error?loadError.message:"โหลดข้อมูลไม่สำเร็จ");
    } finally {
      setLoading(false);
    }
    fetch("/api/operations",{cache:"no-store"}).then(async o=>{
      if(o.ok)setOps(await o.json());
    }).catch(()=>{});
  }
  useEffect(()=>{load()},[]);
  const stats=useMemo(()=>members.reduce((a,m)=>{a[statusOf(m.expiresAt).key]++;return a;},{active:0,expiring:0,expired:0} as Record<string,number>),[members]);
  const filtered=members.filter(m=>`${m.fullName} ${m.phone} ${m.memberCode}`.toLowerCase().includes(search.toLowerCase()));
  function notify(x:string){setToast(x);setTimeout(()=>setToast(""),2400)}

  async function uploadEvidence(file:File|null){if(!file||!file.size)return null;const data=new FormData();data.set("file",file);const r=await fetch("/api/slips",{method:"POST",body:data});const d=await r.json();if(!r.ok)throw new Error(d.error||"อัปโหลดหลักฐานไม่สำเร็จ");return d as {key:string;name:string;contentType:string};}
  async function addMember(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);try{const method=String(fd.get("paymentMethod")||"cash");const file=fd.get("slip") as File|null;if(!file||!file.size){notify(method==="cash"?"กรุณาถ่ายรูปหลักฐานรับเงินสด":"กรุณาแนบสลิปการโอนเงิน");return}const slip=await uploadEvidence(file);fd.delete("slip");const payload={...Object.fromEntries(fd),slipKey:slip?.key,slipName:slip?.name,slipContentType:slip?.contentType};const r=await fetch("/api/members",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok){notify(d.error||"บันทึกไม่สำเร็จ");return}setShowAdd(false);notify(`เพิ่มสมาชิก ${d.memberCode} แล้ว`);await load();}catch(error){notify(error instanceof Error?error.message:"อัปโหลดหลักฐานไม่สำเร็จ")}}
  async function renewMember(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!renew)return;const fd=new FormData(e.currentTarget);try{const method=String(fd.get("paymentMethod")||"cash");const file=fd.get("slip") as File|null;if(!file||!file.size){notify(method==="cash"?"กรุณาถ่ายรูปหลักฐานรับเงินสด":"กรุณาแนบสลิปการโอนเงิน");return}const slip=await uploadEvidence(file);fd.delete("slip");const payload={...Object.fromEntries(fd),slipKey:slip?.key,slipName:slip?.name,slipContentType:slip?.contentType};const r=await fetch(`/api/members/${renew.id}/renew`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok){notify(d.error||"บันทึกไม่สำเร็จ");return}setRenew(null);notify("ต่ออายุสมาชิกเรียบร้อย");await load();}catch(error){notify(error instanceof Error?error.message:"อัปโหลดหลักฐานไม่สำเร็จ")}}
  async function doAction(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!action)return;const fd=new FormData(e.currentTarget);const body={...Object.fromEntries(fd),action:action.kind,memberId:action.member?.id};const r=await fetch("/api/operations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok){notify(d.error||"บันทึกไม่สำเร็จ");return}setAction(null);notify("บันทึกเรียบร้อย");await load();}

  return <main className="app-shell"><div className="phone">
    <header className="topbar"><div className="brand"><div className="brand-mark">F</div><div><b>DEMO GYM</b><span>GYM</span></div></div><div className="manager-area"><div className="manager-chip"><span>MANAGER</span><b>{manager.split(" ")[0]}</b></div><form action="/api/logout" method="post"><button aria-label="ออกจากระบบ">↪</button></form></div></header>
    <div className="content">
      {error&&<div className="error-box"><b>ยังเปิดระบบข้อมูลไม่ได้</b><span>{error}</span><button onClick={load}>ลองใหม่</button></div>}
      {loading&&!error&&<div className="loading">กำลังโหลดข้อมูลสมาชิก…</div>}
      {!loading&&!error&&tab==="home"&&<><RenewalAlerts requests={ops.renewals.filter(x=>x.status==="pending")} members={members} onRenew={setRenew}/><Dashboard stats={stats} total={members.length} onAdd={()=>setShowAdd(true)} onMembers={()=>setTab("members")}/></>} 
      {!loading&&!error&&tab==="members"&&<MemberList members={filtered} search={search} setSearch={setSearch} onAdd={()=>setShowAdd(true)} onRenew={setRenew}/>} 
      {!loading&&!error&&tab==="checkin"&&<Checkin members={members} visits={ops.visits} onCheckin={m=>setAction({kind:"checkin",member:m})}/>} 
      {!loading&&!error&&tab==="pt"&&<PT members={members} ops={ops} onAction={(kind,m)=>setAction({kind,member:m})}/>} 
      {!loading&&!error&&tab==="reports"&&<Reports stats={stats} total={members.length} ops={ops} openDatabase={()=>setTab("database")}/>} 
      {!loading&&!error&&tab==="database"&&<DatabaseAdmin members={members} ops={ops} back={()=>setTab("reports")}/>} 
    </div>
    <nav className="bottom-nav five"><Nav active={tab==="home"} icon="/icons/home.svg" label="หน้าหลัก" onClick={()=>setTab("home")}/><Nav active={tab==="members"} icon="/icons/members.svg" label="สมาชิก" onClick={()=>setTab("members")}/><Nav active={tab==="checkin"} icon="/icons/checkin.svg" label="เช็กอิน" onClick={()=>setTab("checkin")}/><Nav active={tab==="pt"} icon="/icons/pt.svg" label="PT" onClick={()=>setTab("pt")}/><Nav active={tab==="reports"} icon="/icons/reports.svg" label="รายงาน" onClick={()=>setTab("reports")}/></nav>
    {toast&&<div className="toast">✓ {toast}</div>}
    {showAdd&&<Modal title="เพิ่มสมาชิกใหม่" close={()=>setShowAdd(false)}><form onSubmit={addMember}><label>ชื่อ–นามสกุล<input name="fullName" required placeholder="เช่น คุณมินตรา ใจดี"/></label><label>เบอร์โทรศัพท์<input name="phone" required inputMode="tel" placeholder="08X-XXX-XXXX"/></label><label>LINE ID (ถ้ามี)<input name="lineId" placeholder="สำหรับส่งข้อความเตือน"/></label><label>วันที่ชำระเงิน<input name="paidAt" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><PaymentEvidenceFields/><div className="rule-note">Membership 890 บาท • หลักฐานสูงสุด 5 MB</div><button className="main-button">บันทึกและเปิด Membership</button></form></Modal>}
    {renew&&<Modal title={`ต่ออายุ ${renew.fullName}`} close={()=>setRenew(null)}><form onSubmit={renewMember}><div className="warning">วันคงเหลือเดิมจะไม่สะสม Membership ใหม่เริ่มจากวันที่ชำระเงิน</div><label>วันที่ชำระเงิน<input name="paidAt" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><PaymentEvidenceFields/><div className="rule-note">หลักฐานสูงสุด 5 MB และผูกกับรายการชำระเงินนี้</div><button className="main-button">ยืนยันรับเงิน 890 บาท</button></form></Modal>}
    {action&&<ActionModal action={action} close={()=>setAction(null)} submit={doAction}/>} 
  </div></main>
}

function Dashboard({stats,total,onAdd,onMembers}:{stats:Record<string,number>;total:number;onAdd:()=>void;onMembers:()=>void}){return <><div className="greeting"><p>ระบบทดลองใช้งานจริง</p><span>{new Intl.DateTimeFormat("th-TH",{dateStyle:"full"}).format(new Date())}</span></div><section className="hero-card"><div><span>สมาชิกที่ใช้งานอยู่</span><strong>{stats.active}</strong><small>คน</small></div><div className="active-pill">● LIVE DATA</div><p>ข้อมูลบันทึกถาวรและอัปเดตอัตโนมัติ</p><div className="hero-shape">●</div></section><div className="title-row"><h2>เมนูด่วน</h2><button onClick={onMembers}>ดูสมาชิก</button></div><div className="quick-grid two"><button onClick={onAdd}><i className="quick-svg add-member-icon"/><span>เพิ่มสมาชิก</span></button><button onClick={onMembers}><i>฿</i><span>ต่ออายุ / รับเงิน</span></button></div><h2 className="today-title">สถานะสมาชิกทั้งหมด {total} คน</h2><div className="stats"><div><span>Active</span><strong>{stats.active}</strong><small>คน</small></div><div><span>ใกล้หมดอายุ</span><strong>{stats.expiring}</strong><small>คน</small></div><div><span>หมดอายุ</span><strong>{stats.expired}</strong><small>คน</small></div></div></>}

function RenewalAlerts({requests,members,onRenew}:{requests:any[];members:Member[];onRenew:(m:Member)=>void}){if(!requests.length)return null;return <section className="renewal-alert"><b>🔔 รอต่ออายุ {requests.length} คน</b>{requests.slice(0,3).map(r=>{const m=members.find(x=>x.id===r.memberId);return m?<button key={r.id} onClick={()=>onRenew(m)}><span>{m.fullName}</span><strong>รับเงิน 890 บาท →</strong></button>:null})}</section>}

function MemberList({members,search,setSearch,onAdd,onRenew}:{members:Member[];search:string;setSearch:(x:string)=>void;onAdd:()=>void;onRenew:(m:Member)=>void}){return <><div className="page-title"><div><span className="eyebrow">MEMBER DATABASE</span><h1>สมาชิก</h1></div><button className="add-button" onClick={onAdd}>＋ เพิ่ม</button></div><div className="search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ค้นหาชื่อ เบอร์โทร หรือ Member ID"/></div><div className="member-list live">{members.length===0?<div className="empty"><b>ยังไม่มีสมาชิก</b><span>กด “เพิ่ม” เพื่อเริ่มทดลองระบบ</span></div>:members.map(m=>{const s=statusOf(m.expiresAt);return <article className="member" key={m.id}><div className={`avatar ${s.key}`}>{m.fullName.slice(0,1)}</div><div className="member-main"><b>{m.fullName}</b><span>{m.memberCode} · {m.phone}</span><small className={s.key}>{s.label} · ถึง {thaiDate(m.expiresAt)}</small></div><button className="renew-btn" onClick={()=>onRenew(m)}>ต่ออายุ</button></article>})}</div></>}

function Checkin({members,visits,onCheckin}:{members:Member[];visits:any[];onCheckin:(m:Member)=>void}){const [q,setQ]=useState("");const match=members.find(m=>m.memberCode.toLowerCase()===q.trim().toLowerCase()||m.phone===q.trim());return <><div className="page-title"><div><span className="eyebrow">MANAGER BACKUP</span><h1>ช่วยเช็กอิน</h1></div></div><div className="rule-note">ช่องทางสำรองกรณีสมาชิกสแกน QR ไม่ได้</div><div className="search"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="กรอก Member ID หรือเบอร์โทร"/></div>{match&&<section className="action-card"><b>{match.fullName}</b><span>{match.memberCode} · {statusOf(match.expiresAt).label}</span><button onClick={()=>onCheckin(match)}>{statusOf(match.expiresAt).key==="expired"?"แจ้งต่ออายุ":"ช่วย Check-in"}</button></section>}<h2 className="today-title">เช็กอินล่าสุด</h2><div className="kpi-list">{visits.slice(0,6).map(v=><p key={v.id}><span>{members.find(m=>m.id===v.memberId)?.fullName||`Member ${v.memberId}`} · {v.source||"manager"}</span><b>{new Date(v.checkedInAt).toLocaleString("th-TH",{dateStyle:"short",timeStyle:"short"})}</b></p>)}</div></>}

function PT({members,ops,onAction}:{members:Member[];ops:Ops;onAction:(k:string,m:Member)=>void}){return <><div className="page-title"><div><span className="eyebrow">PT & PROGRESS</span><h1>จัดการ PT</h1></div></div><div className="member-list live">{members.map(m=>{const p=ops.packages.find(x=>x.memberId===m.id);const a=ops.assessments.find(x=>x.memberId===m.id);return <article className="member stacked" key={m.id}><div className="member-line"><div className="avatar active">{m.fullName[0]}</div><div className="member-main"><b>{m.fullName}</b><span>{m.memberCode}</span><small>PT คงเหลือ {p?.remainingSessions??0} ครั้ง {a?`· วัดล่าสุด ${thaiDate(a.assessedAt)}`:""}</small></div></div><div className="mini-actions"><button onClick={()=>onAction("buyPt",m)}>ซื้อ PT</button><button onClick={()=>onAction("usePt",m)}>ใช้ Session</button><button onClick={()=>onAction("progress",m)}>Progress</button><button onClick={()=>onAction("followup",m)}>LINE</button></div></article>})}</div></>}

function ActionModal({action,close,submit}:{action:{kind:string;member?:Member};close:()=>void;submit:(e:FormEvent<HTMLFormElement>)=>void}){const title={checkin:"ยืนยัน Check-in",buyPt:"ขาย PT Package",usePt:"บันทึก PT Session",progress:"บันทึก Body Progress",followup:"บันทึกการติดตาม"}[action.kind]||"บันทึก";return <Modal title={`${title} · ${action.member?.fullName}`} close={close}><form onSubmit={submit}>{action.kind==="checkin"&&<div className="rule-note">ระบบจะบันทึกวันและเวลาปัจจุบัน</div>}{action.kind==="buyPt"&&<><div className="rule-note">5,000 บาท · 14 Sessions · ไม่มีวันหมดอายุ</div><label>วันที่ซื้อ<input name="date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><label>ช่องทาง<select name="paymentMethod"><option value="cash">เงินสด</option><option value="transfer">โอนเงิน</option></select></label></>}{action.kind==="usePt"&&<><label>วันที่เทรน<input name="date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></label><label>โปรแกรม<input name="program" placeholder="เช่น Lower body"/></label><div className="form-row"><label>ความเหนื่อย 1–10<input name="effort" type="number" min="1" max="10"/></label><label>อาการเจ็บ<input name="painNote" placeholder="ไม่มี"/></label></div></>}{action.kind==="progress"&&<><div className="form-row"><label>วันที่ประเมิน<input name="date" type="date" defaultValue={new Date().toISOString().slice(0,10)}/></label><label>เป้าหมาย<select name="goal"><option>ลดน้ำหนัก</option><option>เพิ่มกล้ามเนื้อ</option><option>สุขภาพทั่วไป</option></select></label></div><div className="form-row"><label>น้ำหนัก (kg)<input name="weight" type="number" step="0.1"/></label><label>รอบเอว (cm)<input name="waist" type="number" step="0.1"/></label></div><div className="form-row"><label>Body Fat %<input name="bodyFat" type="number" step="0.1"/></label><label>Muscle Mass<input name="muscleMass" type="number" step="0.1"/></label></div><label>Progress Note<input name="note"/></label><label className="consent"><input name="consent" type="checkbox" value="yes"/> สมาชิกยินยอมให้เก็บข้อมูลสุขภาพ</label></>}{action.kind==="followup"&&<><label>ประเภท<select name="type"><option value="renewal">แจ้งต่ออายุ</option><option value="inactive">ไม่มาเกิน 14 วัน</option><option value="pt_balance">PT ใกล้หมด</option></select></label><label>บันทึก<input name="note" placeholder="ผลการติดต่อ"/></label>{action.member?.lineId&&<a className="line-link" target="_blank" href={`https://line.me/R/ti/p/~${action.member.lineId}`}>เปิด LINE</a>}</>}<button className="main-button">ยืนยันบันทึก</button></form></Modal>}

function Reports({stats,total,ops,openDatabase}:{stats:Record<string,number>;total:number;ops:Ops;openDatabase:()=>void}){const rate=total?Math.round(((stats.active+stats.expiring)/total)*100):0;const ptLeft=ops.packages.reduce((s,p)=>s+p.remainingSessions,0);return <><div className="page-title"><div><span className="eyebrow">LIVE REPORT</span><h1>ภาพรวมธุรกิจ</h1></div><button className="add-button" onClick={openDatabase}>ฐานข้อมูล</button></div><div className="report-grid"><div><span>สมาชิกทั้งหมด</span><strong>{total} คน</strong><small>ข้อมูลจริง</small></div><div><span>Active Rate</span><strong>{rate}%</strong><small>รวมใกล้หมดอายุ</small></div><div><span>Check-in</span><strong>{ops.visits.length}</strong><small>100 รายการล่าสุด</small></div><div><span>PT คงเหลือ</span><strong>{ptLeft}</strong><small>Sessions</small></div></div><section className="insight"><div>⚡</div><p><b>สิ่งที่ควรทำวันนี้</b><span>มี {stats.expiring} คนใกล้หมดอายุ และ {ops.packages.filter(p=>p.remainingSessions>0&&p.remainingSessions<=3).length} คน PT ใกล้หมด</span></p></section><h2 className="today-title">ระบบพร้อมใช้</h2><div className="kpi-list"><p><span>Member & Membership</span><b>พร้อมใช้</b></p><p><span>QR/Member Check-in</span><b>พร้อมใช้</b></p><p><span>PT & Body Progress</span><b>พร้อมใช้</b></p><p><span>LINE Follow-up Log</span><b>พร้อมใช้</b></p></div></>}

function DatabaseAdmin({members,ops,back}:{members:Member[];ops:Ops;back:()=>void}){const [table,setTable]=useState("members");const rows:Record<string,any[]>= {members,payments:ops.payments,memberships:ops.memberships,check_ins:ops.visits,pt_packages:ops.packages,pt_sessions:ops.sessions,body_assessments:ops.assessments,follow_ups:ops.followups};const labels:Record<string,string>={members:"สมาชิก",payments:"การชำระเงิน",memberships:"Membership",check_ins:"Check-in",pt_packages:"PT Package",pt_sessions:"PT Sessions",body_assessments:"Body Progress",follow_ups:"Follow-up"};return <><div className="page-title"><div><span className="eyebrow">READ-ONLY DATABASE</span><h1>ฐานข้อมูล</h1></div><button className="period" onClick={back}>← กลับ</button></div><div className="db-tabs">{Object.keys(rows).map(k=><button className={table===k?"selected":""} onClick={()=>setTable(k)} key={k}>{labels[k]} <b>{rows[k]?.length||0}</b></button>)}</div><div className="db-note">ดูข้อมูลอย่างเดียว ป้องกันการลบหรือแก้ไขโดยไม่ตั้งใจ</div><div className="db-list">{!rows[table]?.length?<div className="empty"><b>ยังไม่มีข้อมูล</b><span>{labels[table]}</span></div>:rows[table].map((row,i)=><article key={row.id||i}><div className="db-row-head"><b>#{row.id||i+1}</b><span>{row.fullName||members.find(m=>m.id===row.memberId)?.fullName||"—"}</span></div>{Object.entries(row).filter(([k])=>!['id'].includes(k)).map(([k,v])=><p key={k}><span>{k}</span>{k==="slipKey"&&v?<a href={`/api/slips?key=${encodeURIComponent(String(v))}`} target="_blank" rel="noreferrer">เปิดสลิป</a>:<b>{v===null||v===''?'—':typeof v==='boolean'?(v?'Yes':'No'):String(v)}</b>}</p>)}</article>)}</div></>}

function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modal-backdrop" onClick={close}><section className="sheet" onClick={e=>e.stopPropagation()}><div className="sheet-handle"/><div className="section-heading"><div><span className="eyebrow">MANAGER ACTION</span><h2>{title}</h2></div><button onClick={close}>×</button></div>{children}</section></div>}
function Nav({active,icon,label,onClick}:{active:boolean;icon:string;label:string;onClick:()=>void}){return <button className={active?"active":""} onClick={onClick}><i>{icon.startsWith("/")?<span className="nav-svg" aria-hidden="true" style={{maskImage:`url(${icon})`,WebkitMaskImage:`url(${icon})`}}/>:icon}</i><span>{label}</span></button>}
function PaymentEvidenceFields(){const [method,setMethod]=useState("cash");return <><label>ช่องทางชำระเงิน<select name="paymentMethod" value={method} onChange={e=>setMethod(e.target.value)}><option value="cash">เงินสด</option><option value="transfer">โอนเงิน</option></select></label>{method==="cash"?<label className="camera-evidence"><span>รูปหลักฐานรับเงินสด</span><input key="cash-camera" name="slip" type="file" accept="image/*" capture="environment" required/><small>📷 แตะเพื่อเปิดกล้องและถ่ายรูปหลักฐาน</small></label>:<label><span>สลิปการโอนเงิน</span><input key="transfer-slip" name="slip" type="file" accept="image/png,image/jpeg,application/pdf" required/><small>แนบ JPG, PNG หรือ PDF</small></label>}</>}
