import { boolean, date, integer, pgTable, real, serial, text, timestamp } from "drizzle-orm/pg-core";

const createdAt = () => timestamp("created_at", { withTimezone: true, mode: "string" }).notNull().defaultNow();

export const members = pgTable("members", { id: serial("id").primaryKey(), memberCode: text("member_code").notNull().unique(), fullName: text("full_name").notNull(), phone: text("phone").notNull(), lineId: text("line_id"), createdAt: createdAt() });
export const payments = pgTable("payments", { id: serial("id").primaryKey(), memberId: integer("member_id").notNull().references(() => members.id), amount: integer("amount").notNull(), paidAt: date("paid_at", { mode: "string" }).notNull(), paymentMethod: text("payment_method").notNull().default("cash"), slipKey: text("slip_key"), slipName: text("slip_name"), slipContentType: text("slip_content_type"), recordedBy: text("recorded_by").notNull(), createdAt: createdAt() });
export const memberships = pgTable("memberships", { id: serial("id").primaryKey(), memberId: integer("member_id").notNull().references(() => members.id), paymentId: integer("payment_id").notNull().references(() => payments.id), startsAt: date("starts_at", { mode: "string" }).notNull(), expiresAt: date("expires_at", { mode: "string" }).notNull(), createdAt: createdAt() });
export const checkIns = pgTable("check_ins", { id: serial("id").primaryKey(), memberId: integer("member_id").notNull().references(() => members.id), checkedInAt: timestamp("checked_in_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(), recordedBy: text("recorded_by").notNull(), source: text("source").notNull().default("manager"), reason: text("reason") });
export const renewalRequests = pgTable("renewal_requests", { id: serial("id").primaryKey(), memberId: integer("member_id").notNull().references(() => members.id), status: text("status").notNull().default("pending"), requestedAt: timestamp("requested_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(), resolvedAt: timestamp("resolved_at", { withTimezone: true, mode: "string" }) });
export const ptPackages = pgTable("pt_packages", { id: serial("id").primaryKey(), memberId: integer("member_id").notNull().references(() => members.id), paymentId: integer("payment_id").notNull().references(() => payments.id), totalSessions: integer("total_sessions").notNull().default(14), remainingSessions: integer("remaining_sessions").notNull().default(14), purchasedAt: date("purchased_at", { mode: "string" }).notNull(), createdAt: createdAt() });
export const ptSessions = pgTable("pt_sessions", { id: serial("id").primaryKey(), memberId: integer("member_id").notNull().references(() => members.id), packageId: integer("package_id").notNull().references(() => ptPackages.id), trainedAt: date("trained_at", { mode: "string" }).notNull(), program: text("program"), effort: integer("effort"), painNote: text("pain_note"), recordedBy: text("recorded_by").notNull(), createdAt: createdAt() });
export const bodyAssessments = pgTable("body_assessments", { id: serial("id").primaryKey(), memberId: integer("member_id").notNull().references(() => members.id), assessedAt: date("assessed_at", { mode: "string" }).notNull(), weight: real("weight"), waist: real("waist"), hip: real("hip"), arm: real("arm"), thigh: real("thigh"), bodyFat: real("body_fat"), muscleMass: real("muscle_mass"), goal: text("goal"), note: text("note"), consent: boolean("consent").notNull().default(false), recordedBy: text("recorded_by").notNull(), createdAt: createdAt() });
export const followUps = pgTable("follow_ups", { id: serial("id").primaryKey(), memberId: integer("member_id").notNull().references(() => members.id), type: text("type").notNull(), note: text("note"), contactedAt: timestamp("contacted_at", { withTimezone: true, mode: "string" }).notNull().defaultNow(), recordedBy: text("recorded_by").notNull() });
